server:
  port: 8082

spring:
  application:
    name: product-manager-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vimal-prabhakaran/eureka-discovery-service-info.git
          clone-on-start: true